apiVersion: v1
data:
  datasource-script.cli: |
    # Enable all traces for org.wildfly.security, route all traces to the console, remove the file-handler

    if (outcome == success) of /subsystem=logging:read-resource
      /subsystem=logging/logger=org.wildfly.security:add(level=ALL)
    end-if
    if (outcome == success) of /subsystem=logging/root-logger=ROOT:read-resource
      /subsystem=logging/root-logger=ROOT:write-attribute(name=level,value=INFO)
      /subsystem=logging/root-logger=ROOT:write-attribute(name=handlers,value=[CONSOLE])
    end-if

    if (outcome == success) of /subsystem=logging/periodic-rotating-file-handler=FILE:read-resource
      /subsystem=logging/periodic-rotating-file-handler=FILE:remove
    end-if

    if (outcome == success) of /subsystem=logging/pattern-formatter=PATTERN:read-resource
      /subsystem=logging/pattern-formatter=PATTERN:remove
    end-if

    if (outcome == success) of /subsystem=logging/console-handler=CONSOLE:read-resource
      /subsystem=logging/console-handler=CONSOLE:undefine-attribute(name=level)
    end-if
kind: ConfigMap
metadata:
  name: wildfly-datasource-script
  namespace: default
